name: Build multi-arch image

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        -
            name: Checkout code
            uses: actions/checkout@v2

        -
            name: Set up Docker Buildx
            id: buildx
            uses: crazy-max/ghaction-docker-buildx@v3
            with:
                buildx-version: latest

        -
            name: Login to DockerHub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

        -
            name: Build the image
            run: |
                docker buildx build --push \
                --tag varrrro/libshipyard:latest \
                --platform linux/amd64,linux/arm/v7,linux/arm64 . 
